spring.application.name=springboot-app
# Actuator configuration
management.endpoints.web.exposure.include=health,info
management.info.build.enabled=true
management.info.env.enabled=true
info.app.name=Spring Boot Application
info.app.version=1.0.0
info.app.description=My first Spring Boot app